### ISSUE TITLE
Hashing

### ISSUE THREAD

**Issue by PerhapsSomeone** [1dime/Evie#1]
Your current login and register implementation will not work because bcrypt, like any modern hashing algo, includes an automatic salt, making each hashing result different.
Take a look at password_verify().

**Comment by 1dime** [comment]
So i'd just use password_verify to verify the login information, correct?

**Comment by PerhapsSomeone** [comment]
Yes.
Do take a look at PDO too, it will make everything SQL more comfortable later on.

**Comment by 1dime** [comment]
I know. I made my own PDO helper class because I don't like re-writing code. It's a hell of a lot better than the old mysql functions.

**Comment by 1dime** [comment]
I believe i just updated the project with bcrypt login support too. I'm thinking of making the messaging service essentially the comment section of each published paper, allowing the authors to get more one on one with commenters.

**Comment by 1dime** [comment]
You can make changes to the project if you wish. I am starting on the PDF upload (making a post, but the post is really a paper the authors are publishing) and home page.
